[build]
  publish = "out"
  command = """
    apt-get update && apt-get install -y git-lfs
    git lfs install
    git lfs pull
    next build && next export && npm run generate-sitemap && npm run generate-rss
  """

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
  NODE_ENV = "production"

# Enable compression and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://*.google.com https://*.doubleclick.net https://*.googleadservices.com https://donorbox.org; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com https://*.google.com https://*.doubleclick.net; connect-src 'self' https://www.google-analytics.com https://formspree.io https://*.google.com https://*.doubleclick.net https://*.googleadservices.com; frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://*.google.com https://donorbox.org;"
    
# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[forms]]
  name = "contact"
  action = "/contact-success/"
  [[forms.notifications]]
    email = "shalom@humbleberger.org"
