[build]
  publish = "out"
  command = "npm run build && next export"

# Enable compression and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com;"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[forms]]
  name = "contact"
  action = "/contact-success"
  [[forms.notifications]]
    email = "shalom@humbleberger.org"